# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QC9520_UI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QC9520(object):
    def setupUi(self, QC9520):
        QC9520.setObjectName(_fromUtf8("QC9520"))
        QC9520.resize(900, 629)
        QC9520.setLayoutDirection(QtCore.Qt.LeftToRight)
        QC9520.setIconSize(QtCore.QSize(50, 50))
        QC9520.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(QC9520)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 300, 600))
        self.groupBox.setStyleSheet(_fromUtf8("border: 0px"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.BNC_A = QtGui.QLabel(self.groupBox)
        self.BNC_A.setGeometry(QtCore.QRect(40, 80, 50, 50))
        self.BNC_A.setAutoFillBackground(False)
        self.BNC_A.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_A.setLineWidth(0)
        self.BNC_A.setText(_fromUtf8(""))
        self.BNC_A.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_A.setScaledContents(True)
        self.BNC_A.setObjectName(_fromUtf8("BNC_A"))
        self.BNC_B = QtGui.QLabel(self.groupBox)
        self.BNC_B.setGeometry(QtCore.QRect(140, 80, 50, 50))
        self.BNC_B.setAutoFillBackground(False)
        self.BNC_B.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_B.setLineWidth(0)
        self.BNC_B.setText(_fromUtf8(""))
        self.BNC_B.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_B.setScaledContents(True)
        self.BNC_B.setObjectName(_fromUtf8("BNC_B"))
        self.BNC_D = QtGui.QLabel(self.groupBox)
        self.BNC_D.setGeometry(QtCore.QRect(140, 182, 50, 50))
        self.BNC_D.setAutoFillBackground(False)
        self.BNC_D.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_D.setLineWidth(0)
        self.BNC_D.setText(_fromUtf8(""))
        self.BNC_D.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_D.setScaledContents(True)
        self.BNC_D.setObjectName(_fromUtf8("BNC_D"))
        self.BNC_C = QtGui.QLabel(self.groupBox)
        self.BNC_C.setGeometry(QtCore.QRect(40, 182, 50, 50))
        self.BNC_C.setAutoFillBackground(False)
        self.BNC_C.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_C.setLineWidth(0)
        self.BNC_C.setText(_fromUtf8(""))
        self.BNC_C.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_C.setScaledContents(True)
        self.BNC_C.setObjectName(_fromUtf8("BNC_C"))
        self.BNC_F = QtGui.QLabel(self.groupBox)
        self.BNC_F.setGeometry(QtCore.QRect(140, 285, 50, 50))
        self.BNC_F.setAutoFillBackground(False)
        self.BNC_F.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_F.setLineWidth(0)
        self.BNC_F.setText(_fromUtf8(""))
        self.BNC_F.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_F.setScaledContents(True)
        self.BNC_F.setObjectName(_fromUtf8("BNC_F"))
        self.BNC_E = QtGui.QLabel(self.groupBox)
        self.BNC_E.setGeometry(QtCore.QRect(40, 285, 50, 50))
        self.BNC_E.setAutoFillBackground(False)
        self.BNC_E.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_E.setLineWidth(0)
        self.BNC_E.setText(_fromUtf8(""))
        self.BNC_E.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_E.setScaledContents(True)
        self.BNC_E.setObjectName(_fromUtf8("BNC_E"))
        self.BNC_H = QtGui.QLabel(self.groupBox)
        self.BNC_H.setGeometry(QtCore.QRect(140, 385, 50, 50))
        self.BNC_H.setAutoFillBackground(False)
        self.BNC_H.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_H.setLineWidth(0)
        self.BNC_H.setText(_fromUtf8(""))
        self.BNC_H.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_H.setScaledContents(True)
        self.BNC_H.setObjectName(_fromUtf8("BNC_H"))
        self.BNC_G = QtGui.QLabel(self.groupBox)
        self.BNC_G.setGeometry(QtCore.QRect(40, 385, 50, 50))
        self.BNC_G.setAutoFillBackground(False)
        self.BNC_G.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_G.setLineWidth(0)
        self.BNC_G.setText(_fromUtf8(""))
        self.BNC_G.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_G.setScaledContents(True)
        self.BNC_G.setObjectName(_fromUtf8("BNC_G"))
        self.BNC_B_5 = QtGui.QLabel(self.groupBox)
        self.BNC_B_5.setGeometry(QtCore.QRect(140, 490, 50, 50))
        self.BNC_B_5.setAutoFillBackground(False)
        self.BNC_B_5.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_B_5.setLineWidth(0)
        self.BNC_B_5.setText(_fromUtf8(""))
        self.BNC_B_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_B_5.setScaledContents(True)
        self.BNC_B_5.setObjectName(_fromUtf8("BNC_B_5"))
        self.BNC_gate = QtGui.QLabel(self.groupBox)
        self.BNC_gate.setGeometry(QtCore.QRect(40, 490, 50, 50))
        self.BNC_gate.setAutoFillBackground(False)
        self.BNC_gate.setFrameShadow(QtGui.QFrame.Plain)
        self.BNC_gate.setLineWidth(0)
        self.BNC_gate.setText(_fromUtf8(""))
        self.BNC_gate.setPixmap(QtGui.QPixmap(_fromUtf8(":/connectors/bnc.png")))
        self.BNC_gate.setScaledContents(True)
        self.BNC_gate.setObjectName(_fromUtf8("BNC_gate"))
        self.QC_A = QtGui.QPushButton(self.groupBox)
        self.QC_A.setGeometry(QtCore.QRect(240, 59, 50, 30))
        self.QC_A.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_A_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_A_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_A.setIcon(icon)
        self.QC_A.setIconSize(QtCore.QSize(50, 30))
        self.QC_A.setCheckable(True)
        self.QC_A.setFlat(True)
        self.QC_A.setObjectName(_fromUtf8("QC_A"))
        self.QC_B = QtGui.QPushButton(self.groupBox)
        self.QC_B.setGeometry(QtCore.QRect(240, 114, 50, 30))
        self.QC_B.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_B_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_B_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_B.setIcon(icon1)
        self.QC_B.setIconSize(QtCore.QSize(50, 30))
        self.QC_B.setCheckable(True)
        self.QC_B.setFlat(True)
        self.QC_B.setObjectName(_fromUtf8("QC_B"))
        self.QC_C = QtGui.QPushButton(self.groupBox)
        self.QC_C.setGeometry(QtCore.QRect(240, 161, 50, 30))
        self.QC_C.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_C_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_C_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_C.setIcon(icon2)
        self.QC_C.setIconSize(QtCore.QSize(50, 30))
        self.QC_C.setCheckable(True)
        self.QC_C.setFlat(True)
        self.QC_C.setObjectName(_fromUtf8("QC_C"))
        self.QC_D = QtGui.QPushButton(self.groupBox)
        self.QC_D.setGeometry(QtCore.QRect(240, 214, 50, 30))
        self.QC_D.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_D_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_D_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_D.setIcon(icon3)
        self.QC_D.setIconSize(QtCore.QSize(50, 30))
        self.QC_D.setCheckable(True)
        self.QC_D.setFlat(True)
        self.QC_D.setObjectName(_fromUtf8("QC_D"))
        self.QC_E = QtGui.QPushButton(self.groupBox)
        self.QC_E.setGeometry(QtCore.QRect(240, 264, 50, 30))
        self.QC_E.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_E_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_E_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_E.setIcon(icon4)
        self.QC_E.setIconSize(QtCore.QSize(50, 30))
        self.QC_E.setCheckable(True)
        self.QC_E.setFlat(True)
        self.QC_E.setObjectName(_fromUtf8("QC_E"))
        self.QC_F = QtGui.QPushButton(self.groupBox)
        self.QC_F.setGeometry(QtCore.QRect(240, 318, 50, 30))
        self.QC_F.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_F_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_F_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_F.setIcon(icon5)
        self.QC_F.setIconSize(QtCore.QSize(50, 30))
        self.QC_F.setCheckable(True)
        self.QC_F.setFlat(True)
        self.QC_F.setObjectName(_fromUtf8("QC_F"))
        self.QC_G = QtGui.QPushButton(self.groupBox)
        self.QC_G.setGeometry(QtCore.QRect(240, 366, 50, 30))
        self.QC_G.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_G_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_G_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_G.setIcon(icon6)
        self.QC_G.setIconSize(QtCore.QSize(50, 30))
        self.QC_G.setCheckable(True)
        self.QC_G.setFlat(True)
        self.QC_G.setObjectName(_fromUtf8("QC_G"))
        self.QC_H = QtGui.QPushButton(self.groupBox)
        self.QC_H.setGeometry(QtCore.QRect(240, 421, 50, 30))
        self.QC_H.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_H_off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_H_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_H.setIcon(icon7)
        self.QC_H.setIconSize(QtCore.QSize(50, 30))
        self.QC_H.setCheckable(True)
        self.QC_H.setFlat(True)
        self.QC_H.setObjectName(_fromUtf8("QC_H"))
        self.QC_gate = QtGui.QPushButton(self.groupBox)
        self.QC_gate.setGeometry(QtCore.QRect(240, 469, 50, 30))
        self.QC_gate.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_gate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_gate_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_gate.setIcon(icon8)
        self.QC_gate.setIconSize(QtCore.QSize(50, 30))
        self.QC_gate.setCheckable(True)
        self.QC_gate.setFlat(True)
        self.QC_gate.setObjectName(_fromUtf8("QC_gate"))
        self.QC_trig = QtGui.QPushButton(self.groupBox)
        self.QC_trig.setGeometry(QtCore.QRect(240, 523, 50, 30))
        self.QC_trig.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_trig.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_trig_on.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.QC_trig.setIcon(icon9)
        self.QC_trig.setIconSize(QtCore.QSize(50, 30))
        self.QC_trig.setCheckable(True)
        self.QC_trig.setFlat(True)
        self.QC_trig.setObjectName(_fromUtf8("QC_trig"))
        self.background = QtGui.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.background.setText(_fromUtf8(""))
        self.background.setPixmap(QtGui.QPixmap(_fromUtf8(":/background/QC_Background.png")))
        self.background.setScaledContents(False)
        self.background.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.background.setObjectName(_fromUtf8("background"))
        self.dial = QtGui.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(600, 270, 125, 125))
        self.dial.setStyleSheet(_fromUtf8(""))
        self.dial.setMaximum(9)
        self.dial.setSingleStep(0)
        self.dial.setWrapping(True)
        self.dial.setNotchesVisible(False)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.power_button = QtGui.QPushButton(self.centralwidget)
        self.power_button.setEnabled(True)
        self.power_button.setGeometry(QtCore.QRect(830, 20, 50, 50))
        self.power_button.setAutoFillBackground(False)
        self.power_button.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/power/QC9520_power_off.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/power/QC9520_power_on.svg")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.power_button.setIcon(icon10)
        self.power_button.setIconSize(QtCore.QSize(50, 50))
        self.power_button.setCheckable(True)
        self.power_button.setChecked(False)
        self.power_button.setAutoDefault(False)
        self.power_button.setDefault(False)
        self.power_button.setFlat(True)
        self.power_button.setObjectName(_fromUtf8("power_button"))
        self.QC_up = QtGui.QPushButton(self.centralwidget)
        self.QC_up.setGeometry(QtCore.QRect(618, 451, 50, 30))
        self.QC_up.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_uo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_up.setIcon(icon11)
        self.QC_up.setIconSize(QtCore.QSize(50, 30))
        self.QC_up.setCheckable(False)
        self.QC_up.setFlat(True)
        self.QC_up.setObjectName(_fromUtf8("QC_up"))
        self.QC_right = QtGui.QPushButton(self.centralwidget)
        self.QC_right.setGeometry(QtCore.QRect(683, 496, 50, 30))
        self.QC_right.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_right.setIcon(icon12)
        self.QC_right.setIconSize(QtCore.QSize(50, 30))
        self.QC_right.setCheckable(False)
        self.QC_right.setFlat(True)
        self.QC_right.setObjectName(_fromUtf8("QC_right"))
        self.QC_left = QtGui.QPushButton(self.centralwidget)
        self.QC_left.setGeometry(QtCore.QRect(553, 496, 50, 30))
        self.QC_left.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_left.setIcon(icon13)
        self.QC_left.setIconSize(QtCore.QSize(50, 30))
        self.QC_left.setCheckable(False)
        self.QC_left.setFlat(True)
        self.QC_left.setObjectName(_fromUtf8("QC_left"))
        self.QC_down = QtGui.QPushButton(self.centralwidget)
        self.QC_down.setGeometry(QtCore.QRect(618, 541, 50, 30))
        self.QC_down.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_down.setIcon(icon14)
        self.QC_down.setIconSize(QtCore.QSize(50, 30))
        self.QC_down.setCheckable(False)
        self.QC_down.setFlat(True)
        self.QC_down.setObjectName(_fromUtf8("QC_down"))
        self.QC_next = QtGui.QPushButton(self.centralwidget)
        self.QC_next.setGeometry(QtCore.QRect(618, 496, 50, 30))
        self.QC_next.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_next.setIcon(icon15)
        self.QC_next.setIconSize(QtCore.QSize(50, 30))
        self.QC_next.setCheckable(False)
        self.QC_next.setFlat(True)
        self.QC_next.setObjectName(_fromUtf8("QC_next"))
        self.groupNumbers = QtGui.QGroupBox(self.centralwidget)
        self.groupNumbers.setEnabled(True)
        self.groupNumbers.setGeometry(QtCore.QRect(340, 310, 180, 250))
        self.groupNumbers.setAutoFillBackground(False)
        self.groupNumbers.setStyleSheet(_fromUtf8("border: 0px"))
        self.groupNumbers.setTitle(_fromUtf8(""))
        self.groupNumbers.setObjectName(_fromUtf8("groupNumbers"))
        self.QC_clr = QtGui.QPushButton(self.groupNumbers)
        self.QC_clr.setGeometry(QtCore.QRect(0, 200, 50, 45))
        self.QC_clr.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_clr.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_clr.setIcon(icon16)
        self.QC_clr.setIconSize(QtCore.QSize(50, 45))
        self.QC_clr.setCheckable(False)
        self.QC_clr.setFlat(True)
        self.QC_clr.setObjectName(_fromUtf8("QC_clr"))
        self.QC_9 = QtGui.QPushButton(self.groupNumbers)
        self.QC_9.setGeometry(QtCore.QRect(130, 100, 50, 45))
        self.QC_9.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_9.setIcon(icon17)
        self.QC_9.setIconSize(QtCore.QSize(50, 45))
        self.QC_9.setCheckable(False)
        self.QC_9.setFlat(True)
        self.QC_9.setObjectName(_fromUtf8("QC_9"))
        self.QC_underscore = QtGui.QPushButton(self.groupNumbers)
        self.QC_underscore.setGeometry(QtCore.QRect(130, 150, 50, 45))
        self.QC_underscore.setText(_fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_underscore.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_underscore.setIcon(icon18)
        self.QC_underscore.setIconSize(QtCore.QSize(50, 45))
        self.QC_underscore.setCheckable(False)
        self.QC_underscore.setFlat(True)
        self.QC_underscore.setObjectName(_fromUtf8("QC_underscore"))
        self.QC_3 = QtGui.QPushButton(self.groupNumbers)
        self.QC_3.setGeometry(QtCore.QRect(130, 0, 50, 45))
        self.QC_3.setText(_fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_3.setIcon(icon19)
        self.QC_3.setIconSize(QtCore.QSize(50, 45))
        self.QC_3.setCheckable(False)
        self.QC_3.setFlat(True)
        self.QC_3.setObjectName(_fromUtf8("QC_3"))
        self.QC_period = QtGui.QPushButton(self.groupNumbers)
        self.QC_period.setGeometry(QtCore.QRect(0, 150, 50, 45))
        self.QC_period.setText(_fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_period.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_period.setIcon(icon20)
        self.QC_period.setIconSize(QtCore.QSize(50, 45))
        self.QC_period.setCheckable(False)
        self.QC_period.setFlat(True)
        self.QC_period.setObjectName(_fromUtf8("QC_period"))
        self.QC_6 = QtGui.QPushButton(self.groupNumbers)
        self.QC_6.setGeometry(QtCore.QRect(130, 50, 50, 45))
        self.QC_6.setText(_fromUtf8(""))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_6.setIcon(icon21)
        self.QC_6.setIconSize(QtCore.QSize(50, 45))
        self.QC_6.setCheckable(False)
        self.QC_6.setFlat(True)
        self.QC_6.setObjectName(_fromUtf8("QC_6"))
        self.QC_7 = QtGui.QPushButton(self.groupNumbers)
        self.QC_7.setGeometry(QtCore.QRect(0, 100, 50, 45))
        self.QC_7.setText(_fromUtf8(""))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_7.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_7.setIcon(icon22)
        self.QC_7.setIconSize(QtCore.QSize(50, 45))
        self.QC_7.setCheckable(False)
        self.QC_7.setFlat(True)
        self.QC_7.setObjectName(_fromUtf8("QC_7"))
        self.QC_return = QtGui.QPushButton(self.groupNumbers)
        self.QC_return.setGeometry(QtCore.QRect(130, 200, 50, 45))
        self.QC_return.setText(_fromUtf8(""))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_return.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_return.setIcon(icon23)
        self.QC_return.setIconSize(QtCore.QSize(50, 45))
        self.QC_return.setCheckable(False)
        self.QC_return.setFlat(True)
        self.QC_return.setObjectName(_fromUtf8("QC_return"))
        self.QC_func = QtGui.QPushButton(self.groupNumbers)
        self.QC_func.setGeometry(QtCore.QRect(65, 200, 50, 45))
        self.QC_func.setText(_fromUtf8(""))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_func.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_func.setIcon(icon24)
        self.QC_func.setIconSize(QtCore.QSize(50, 45))
        self.QC_func.setCheckable(True)
        self.QC_func.setFlat(True)
        self.QC_func.setObjectName(_fromUtf8("QC_func"))
        self.QC_2 = QtGui.QPushButton(self.groupNumbers)
        self.QC_2.setGeometry(QtCore.QRect(65, 0, 50, 45))
        self.QC_2.setText(_fromUtf8(""))
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_2.setIcon(icon25)
        self.QC_2.setIconSize(QtCore.QSize(50, 45))
        self.QC_2.setCheckable(False)
        self.QC_2.setFlat(True)
        self.QC_2.setObjectName(_fromUtf8("QC_2"))
        self.QC_5 = QtGui.QPushButton(self.groupNumbers)
        self.QC_5.setGeometry(QtCore.QRect(65, 50, 50, 45))
        self.QC_5.setText(_fromUtf8(""))
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_5.setIcon(icon26)
        self.QC_5.setIconSize(QtCore.QSize(50, 45))
        self.QC_5.setCheckable(False)
        self.QC_5.setFlat(True)
        self.QC_5.setObjectName(_fromUtf8("QC_5"))
        self.QC_1 = QtGui.QPushButton(self.groupNumbers)
        self.QC_1.setGeometry(QtCore.QRect(0, 0, 50, 45))
        self.QC_1.setText(_fromUtf8(""))
        self.QC_1.setIcon(icon17)
        self.QC_1.setIconSize(QtCore.QSize(50, 45))
        self.QC_1.setCheckable(False)
        self.QC_1.setFlat(True)
        self.QC_1.setObjectName(_fromUtf8("QC_1"))
        self.QC_4 = QtGui.QPushButton(self.groupNumbers)
        self.QC_4.setGeometry(QtCore.QRect(0, 50, 50, 45))
        self.QC_4.setText(_fromUtf8(""))
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_4.setIcon(icon27)
        self.QC_4.setIconSize(QtCore.QSize(50, 45))
        self.QC_4.setCheckable(False)
        self.QC_4.setFlat(True)
        self.QC_4.setObjectName(_fromUtf8("QC_4"))
        self.QC_0 = QtGui.QPushButton(self.groupNumbers)
        self.QC_0.setGeometry(QtCore.QRect(65, 150, 50, 45))
        self.QC_0.setText(_fromUtf8(""))
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_0.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_0.setIcon(icon28)
        self.QC_0.setIconSize(QtCore.QSize(50, 45))
        self.QC_0.setCheckable(False)
        self.QC_0.setFlat(True)
        self.QC_0.setObjectName(_fromUtf8("QC_0"))
        self.QC_8 = QtGui.QPushButton(self.groupNumbers)
        self.QC_8.setGeometry(QtCore.QRect(65, 100, 50, 45))
        self.QC_8.setText(_fromUtf8(""))
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/buttons/QC_9.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QC_8.setIcon(icon29)
        self.QC_8.setIconSize(QtCore.QSize(50, 45))
        self.QC_8.setCheckable(False)
        self.QC_8.setFlat(True)
        self.QC_8.setObjectName(_fromUtf8("QC_8"))
        self.group_line1 = QtGui.QGroupBox(self.centralwidget)
        self.group_line1.setGeometry(QtCore.QRect(370, 152, 360, 32))
        self.group_line1.setStyleSheet(_fromUtf8("border: 0px"))
        self.group_line1.setTitle(_fromUtf8(""))
        self.group_line1.setObjectName(_fromUtf8("group_line1"))
        self.lcd_1_1 = QtGui.QLabel(self.group_line1)
        self.lcd_1_1.setGeometry(QtCore.QRect(18, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_1.setFont(font)
        self.lcd_1_1.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_1.setLineWidth(0)
        self.lcd_1_1.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_1.setObjectName(_fromUtf8("lcd_1_1"))
        self.lcd_1_2 = QtGui.QLabel(self.group_line1)
        self.lcd_1_2.setGeometry(QtCore.QRect(36, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_2.setFont(font)
        self.lcd_1_2.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_2.setLineWidth(0)
        self.lcd_1_2.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_2.setObjectName(_fromUtf8("lcd_1_2"))
        self.lcd_1_3 = QtGui.QLabel(self.group_line1)
        self.lcd_1_3.setGeometry(QtCore.QRect(54, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_3.setFont(font)
        self.lcd_1_3.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_3.setLineWidth(0)
        self.lcd_1_3.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_3.setObjectName(_fromUtf8("lcd_1_3"))
        self.lcd_1_4 = QtGui.QLabel(self.group_line1)
        self.lcd_1_4.setGeometry(QtCore.QRect(72, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_4.setFont(font)
        self.lcd_1_4.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_4.setLineWidth(0)
        self.lcd_1_4.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_4.setObjectName(_fromUtf8("lcd_1_4"))
        self.lcd_1_5 = QtGui.QLabel(self.group_line1)
        self.lcd_1_5.setGeometry(QtCore.QRect(90, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_5.setFont(font)
        self.lcd_1_5.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_5.setLineWidth(0)
        self.lcd_1_5.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_5.setObjectName(_fromUtf8("lcd_1_5"))
        self.lcd_1_6 = QtGui.QLabel(self.group_line1)
        self.lcd_1_6.setGeometry(QtCore.QRect(108, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_6.setFont(font)
        self.lcd_1_6.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_6.setLineWidth(0)
        self.lcd_1_6.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_6.setObjectName(_fromUtf8("lcd_1_6"))
        self.lcd_1_7 = QtGui.QLabel(self.group_line1)
        self.lcd_1_7.setGeometry(QtCore.QRect(126, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_7.setFont(font)
        self.lcd_1_7.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_7.setLineWidth(0)
        self.lcd_1_7.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_7.setObjectName(_fromUtf8("lcd_1_7"))
        self.lcd_1_8 = QtGui.QLabel(self.group_line1)
        self.lcd_1_8.setGeometry(QtCore.QRect(144, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_8.setFont(font)
        self.lcd_1_8.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_8.setLineWidth(0)
        self.lcd_1_8.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_8.setObjectName(_fromUtf8("lcd_1_8"))
        self.lcd_1_9 = QtGui.QLabel(self.group_line1)
        self.lcd_1_9.setGeometry(QtCore.QRect(162, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_9.setFont(font)
        self.lcd_1_9.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_9.setLineWidth(0)
        self.lcd_1_9.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_9.setObjectName(_fromUtf8("lcd_1_9"))
        self.lcd_1_10 = QtGui.QLabel(self.group_line1)
        self.lcd_1_10.setGeometry(QtCore.QRect(180, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_10.setFont(font)
        self.lcd_1_10.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_10.setLineWidth(0)
        self.lcd_1_10.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_10.setObjectName(_fromUtf8("lcd_1_10"))
        self.lcd_1_11 = QtGui.QLabel(self.group_line1)
        self.lcd_1_11.setGeometry(QtCore.QRect(198, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_11.setFont(font)
        self.lcd_1_11.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_11.setLineWidth(0)
        self.lcd_1_11.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_11.setObjectName(_fromUtf8("lcd_1_11"))
        self.lcd_1_12 = QtGui.QLabel(self.group_line1)
        self.lcd_1_12.setGeometry(QtCore.QRect(216, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_12.setFont(font)
        self.lcd_1_12.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_12.setLineWidth(0)
        self.lcd_1_12.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_12.setObjectName(_fromUtf8("lcd_1_12"))
        self.lcd_1_13 = QtGui.QLabel(self.group_line1)
        self.lcd_1_13.setGeometry(QtCore.QRect(234, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_13.setFont(font)
        self.lcd_1_13.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_13.setLineWidth(0)
        self.lcd_1_13.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_13.setObjectName(_fromUtf8("lcd_1_13"))
        self.lcd_1_14 = QtGui.QLabel(self.group_line1)
        self.lcd_1_14.setGeometry(QtCore.QRect(252, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_14.setFont(font)
        self.lcd_1_14.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_14.setLineWidth(0)
        self.lcd_1_14.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_14.setObjectName(_fromUtf8("lcd_1_14"))
        self.lcd_1_15 = QtGui.QLabel(self.group_line1)
        self.lcd_1_15.setGeometry(QtCore.QRect(270, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_15.setFont(font)
        self.lcd_1_15.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_15.setLineWidth(0)
        self.lcd_1_15.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_15.setObjectName(_fromUtf8("lcd_1_15"))
        self.lcd_1_16 = QtGui.QLabel(self.group_line1)
        self.lcd_1_16.setGeometry(QtCore.QRect(288, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_16.setFont(font)
        self.lcd_1_16.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_16.setLineWidth(0)
        self.lcd_1_16.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_16.setObjectName(_fromUtf8("lcd_1_16"))
        self.lcd_1_17 = QtGui.QLabel(self.group_line1)
        self.lcd_1_17.setGeometry(QtCore.QRect(306, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_17.setFont(font)
        self.lcd_1_17.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_17.setLineWidth(0)
        self.lcd_1_17.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_17.setObjectName(_fromUtf8("lcd_1_17"))
        self.lcd_1_18 = QtGui.QLabel(self.group_line1)
        self.lcd_1_18.setGeometry(QtCore.QRect(324, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_18.setFont(font)
        self.lcd_1_18.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_18.setLineWidth(0)
        self.lcd_1_18.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_18.setObjectName(_fromUtf8("lcd_1_18"))
        self.lcd_1_19 = QtGui.QLabel(self.group_line1)
        self.lcd_1_19.setGeometry(QtCore.QRect(342, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_19.setFont(font)
        self.lcd_1_19.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_19.setLineWidth(0)
        self.lcd_1_19.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_19.setObjectName(_fromUtf8("lcd_1_19"))
        self.lcd_1_0 = QtGui.QLabel(self.group_line1)
        self.lcd_1_0.setGeometry(QtCore.QRect(0, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_1_0.setFont(font)
        self.lcd_1_0.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_1_0.setLineWidth(0)
        self.lcd_1_0.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_1_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_1_0.setObjectName(_fromUtf8("lcd_1_0"))
        self.lcd_1_1.raise_()
        self.lcd_1_2.raise_()
        self.lcd_1_3.raise_()
        self.lcd_1_4.raise_()
        self.lcd_1_5.raise_()
        self.lcd_1_6.raise_()
        self.lcd_1_7.raise_()
        self.lcd_1_8.raise_()
        self.lcd_1_9.raise_()
        self.lcd_1_10.raise_()
        self.lcd_1_11.raise_()
        self.lcd_1_12.raise_()
        self.lcd_1_13.raise_()
        self.lcd_1_14.raise_()
        self.lcd_1_15.raise_()
        self.background.raise_()
        self.lcd_1_16.raise_()
        self.lcd_1_17.raise_()
        self.lcd_1_18.raise_()
        self.lcd_1_19.raise_()
        self.lcd_1_0.raise_()
        self.group_line2 = QtGui.QGroupBox(self.centralwidget)
        self.group_line2.setGeometry(QtCore.QRect(370, 182, 360, 32))
        self.group_line2.setStyleSheet(_fromUtf8("border: 0px"))
        self.group_line2.setTitle(_fromUtf8(""))
        self.group_line2.setObjectName(_fromUtf8("group_line2"))
        self.lcd_2_1 = QtGui.QLabel(self.group_line2)
        self.lcd_2_1.setGeometry(QtCore.QRect(18, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_1.setFont(font)
        self.lcd_2_1.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_1.setLineWidth(0)
        self.lcd_2_1.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_1.setObjectName(_fromUtf8("lcd_2_1"))
        self.lcd_2_2 = QtGui.QLabel(self.group_line2)
        self.lcd_2_2.setGeometry(QtCore.QRect(36, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_2.setFont(font)
        self.lcd_2_2.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_2.setLineWidth(0)
        self.lcd_2_2.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_2.setObjectName(_fromUtf8("lcd_2_2"))
        self.lcd_2_3 = QtGui.QLabel(self.group_line2)
        self.lcd_2_3.setGeometry(QtCore.QRect(54, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_3.setFont(font)
        self.lcd_2_3.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_3.setLineWidth(0)
        self.lcd_2_3.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_3.setObjectName(_fromUtf8("lcd_2_3"))
        self.lcd_2_4 = QtGui.QLabel(self.group_line2)
        self.lcd_2_4.setGeometry(QtCore.QRect(72, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_4.setFont(font)
        self.lcd_2_4.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_4.setLineWidth(0)
        self.lcd_2_4.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_4.setObjectName(_fromUtf8("lcd_2_4"))
        self.lcd_2_5 = QtGui.QLabel(self.group_line2)
        self.lcd_2_5.setGeometry(QtCore.QRect(90, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_5.setFont(font)
        self.lcd_2_5.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_5.setLineWidth(0)
        self.lcd_2_5.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_5.setObjectName(_fromUtf8("lcd_2_5"))
        self.lcd_2_6 = QtGui.QLabel(self.group_line2)
        self.lcd_2_6.setGeometry(QtCore.QRect(108, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_6.setFont(font)
        self.lcd_2_6.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_6.setLineWidth(0)
        self.lcd_2_6.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_6.setObjectName(_fromUtf8("lcd_2_6"))
        self.lcd_2_7 = QtGui.QLabel(self.group_line2)
        self.lcd_2_7.setGeometry(QtCore.QRect(126, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_7.setFont(font)
        self.lcd_2_7.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_7.setLineWidth(0)
        self.lcd_2_7.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_7.setObjectName(_fromUtf8("lcd_2_7"))
        self.lcd_2_8 = QtGui.QLabel(self.group_line2)
        self.lcd_2_8.setGeometry(QtCore.QRect(144, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_8.setFont(font)
        self.lcd_2_8.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_8.setLineWidth(0)
        self.lcd_2_8.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_8.setObjectName(_fromUtf8("lcd_2_8"))
        self.lcd_2_9 = QtGui.QLabel(self.group_line2)
        self.lcd_2_9.setGeometry(QtCore.QRect(162, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_9.setFont(font)
        self.lcd_2_9.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_9.setLineWidth(0)
        self.lcd_2_9.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_9.setObjectName(_fromUtf8("lcd_2_9"))
        self.lcd_2_10 = QtGui.QLabel(self.group_line2)
        self.lcd_2_10.setGeometry(QtCore.QRect(180, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_10.setFont(font)
        self.lcd_2_10.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_10.setLineWidth(0)
        self.lcd_2_10.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_10.setObjectName(_fromUtf8("lcd_2_10"))
        self.lcd_2_11 = QtGui.QLabel(self.group_line2)
        self.lcd_2_11.setGeometry(QtCore.QRect(198, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_11.setFont(font)
        self.lcd_2_11.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_11.setLineWidth(0)
        self.lcd_2_11.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_11.setObjectName(_fromUtf8("lcd_2_11"))
        self.lcd_2_12 = QtGui.QLabel(self.group_line2)
        self.lcd_2_12.setGeometry(QtCore.QRect(216, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_12.setFont(font)
        self.lcd_2_12.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_12.setLineWidth(0)
        self.lcd_2_12.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_12.setObjectName(_fromUtf8("lcd_2_12"))
        self.lcd_2_13 = QtGui.QLabel(self.group_line2)
        self.lcd_2_13.setGeometry(QtCore.QRect(234, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_13.setFont(font)
        self.lcd_2_13.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_13.setLineWidth(0)
        self.lcd_2_13.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_13.setObjectName(_fromUtf8("lcd_2_13"))
        self.lcd_2_14 = QtGui.QLabel(self.group_line2)
        self.lcd_2_14.setGeometry(QtCore.QRect(252, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_14.setFont(font)
        self.lcd_2_14.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_14.setLineWidth(0)
        self.lcd_2_14.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_14.setObjectName(_fromUtf8("lcd_2_14"))
        self.lcd_2_15 = QtGui.QLabel(self.group_line2)
        self.lcd_2_15.setGeometry(QtCore.QRect(270, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_15.setFont(font)
        self.lcd_2_15.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_15.setLineWidth(0)
        self.lcd_2_15.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_15.setObjectName(_fromUtf8("lcd_2_15"))
        self.lcd_2_16 = QtGui.QLabel(self.group_line2)
        self.lcd_2_16.setGeometry(QtCore.QRect(288, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_16.setFont(font)
        self.lcd_2_16.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_16.setLineWidth(0)
        self.lcd_2_16.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_16.setObjectName(_fromUtf8("lcd_2_16"))
        self.lcd_2_17 = QtGui.QLabel(self.group_line2)
        self.lcd_2_17.setGeometry(QtCore.QRect(306, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_17.setFont(font)
        self.lcd_2_17.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_17.setLineWidth(0)
        self.lcd_2_17.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_17.setObjectName(_fromUtf8("lcd_2_17"))
        self.lcd_2_18 = QtGui.QLabel(self.group_line2)
        self.lcd_2_18.setGeometry(QtCore.QRect(324, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_18.setFont(font)
        self.lcd_2_18.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_18.setLineWidth(0)
        self.lcd_2_18.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_18.setObjectName(_fromUtf8("lcd_2_18"))
        self.lcd_2_19 = QtGui.QLabel(self.group_line2)
        self.lcd_2_19.setGeometry(QtCore.QRect(342, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_19.setFont(font)
        self.lcd_2_19.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_19.setLineWidth(0)
        self.lcd_2_19.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_19.setObjectName(_fromUtf8("lcd_2_19"))
        self.lcd_2_0 = QtGui.QLabel(self.group_line2)
        self.lcd_2_0.setGeometry(QtCore.QRect(0, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_2_0.setFont(font)
        self.lcd_2_0.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_2_0.setLineWidth(0)
        self.lcd_2_0.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_2_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_2_0.setObjectName(_fromUtf8("lcd_2_0"))
        self.group_line3 = QtGui.QGroupBox(self.centralwidget)
        self.group_line3.setGeometry(QtCore.QRect(370, 212, 360, 32))
        self.group_line3.setStyleSheet(_fromUtf8("border: 0px"))
        self.group_line3.setTitle(_fromUtf8(""))
        self.group_line3.setObjectName(_fromUtf8("group_line3"))
        self.lcd_3_1 = QtGui.QLabel(self.group_line3)
        self.lcd_3_1.setGeometry(QtCore.QRect(18, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_1.setFont(font)
        self.lcd_3_1.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_1.setLineWidth(0)
        self.lcd_3_1.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_1.setObjectName(_fromUtf8("lcd_3_1"))
        self.lcd_3_2 = QtGui.QLabel(self.group_line3)
        self.lcd_3_2.setGeometry(QtCore.QRect(36, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_2.setFont(font)
        self.lcd_3_2.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_2.setLineWidth(0)
        self.lcd_3_2.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_2.setObjectName(_fromUtf8("lcd_3_2"))
        self.lcd_3_3 = QtGui.QLabel(self.group_line3)
        self.lcd_3_3.setGeometry(QtCore.QRect(54, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_3.setFont(font)
        self.lcd_3_3.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_3.setLineWidth(0)
        self.lcd_3_3.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_3.setObjectName(_fromUtf8("lcd_3_3"))
        self.lcd_3_4 = QtGui.QLabel(self.group_line3)
        self.lcd_3_4.setGeometry(QtCore.QRect(72, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_4.setFont(font)
        self.lcd_3_4.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_4.setLineWidth(0)
        self.lcd_3_4.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_4.setObjectName(_fromUtf8("lcd_3_4"))
        self.lcd_3_5 = QtGui.QLabel(self.group_line3)
        self.lcd_3_5.setGeometry(QtCore.QRect(90, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_5.setFont(font)
        self.lcd_3_5.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_5.setLineWidth(0)
        self.lcd_3_5.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_5.setObjectName(_fromUtf8("lcd_3_5"))
        self.lcd_3_6 = QtGui.QLabel(self.group_line3)
        self.lcd_3_6.setGeometry(QtCore.QRect(108, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_6.setFont(font)
        self.lcd_3_6.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_6.setLineWidth(0)
        self.lcd_3_6.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_6.setObjectName(_fromUtf8("lcd_3_6"))
        self.lcd_3_7 = QtGui.QLabel(self.group_line3)
        self.lcd_3_7.setGeometry(QtCore.QRect(126, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_7.setFont(font)
        self.lcd_3_7.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_7.setLineWidth(0)
        self.lcd_3_7.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_7.setObjectName(_fromUtf8("lcd_3_7"))
        self.lcd_3_8 = QtGui.QLabel(self.group_line3)
        self.lcd_3_8.setGeometry(QtCore.QRect(144, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_8.setFont(font)
        self.lcd_3_8.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_8.setLineWidth(0)
        self.lcd_3_8.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_8.setObjectName(_fromUtf8("lcd_3_8"))
        self.lcd_3_9 = QtGui.QLabel(self.group_line3)
        self.lcd_3_9.setGeometry(QtCore.QRect(162, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_9.setFont(font)
        self.lcd_3_9.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_9.setLineWidth(0)
        self.lcd_3_9.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_9.setObjectName(_fromUtf8("lcd_3_9"))
        self.lcd_3_10 = QtGui.QLabel(self.group_line3)
        self.lcd_3_10.setGeometry(QtCore.QRect(180, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_10.setFont(font)
        self.lcd_3_10.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_10.setLineWidth(0)
        self.lcd_3_10.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_10.setObjectName(_fromUtf8("lcd_3_10"))
        self.lcd_3_11 = QtGui.QLabel(self.group_line3)
        self.lcd_3_11.setGeometry(QtCore.QRect(198, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_11.setFont(font)
        self.lcd_3_11.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_11.setLineWidth(0)
        self.lcd_3_11.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_11.setObjectName(_fromUtf8("lcd_3_11"))
        self.lcd_3_12 = QtGui.QLabel(self.group_line3)
        self.lcd_3_12.setGeometry(QtCore.QRect(216, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_12.setFont(font)
        self.lcd_3_12.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_12.setLineWidth(0)
        self.lcd_3_12.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_12.setObjectName(_fromUtf8("lcd_3_12"))
        self.lcd_3_13 = QtGui.QLabel(self.group_line3)
        self.lcd_3_13.setGeometry(QtCore.QRect(234, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_13.setFont(font)
        self.lcd_3_13.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_13.setLineWidth(0)
        self.lcd_3_13.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_13.setObjectName(_fromUtf8("lcd_3_13"))
        self.lcd_3_14 = QtGui.QLabel(self.group_line3)
        self.lcd_3_14.setGeometry(QtCore.QRect(252, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_14.setFont(font)
        self.lcd_3_14.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_14.setLineWidth(0)
        self.lcd_3_14.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_14.setObjectName(_fromUtf8("lcd_3_14"))
        self.lcd_3_15 = QtGui.QLabel(self.group_line3)
        self.lcd_3_15.setGeometry(QtCore.QRect(270, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_15.setFont(font)
        self.lcd_3_15.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_15.setLineWidth(0)
        self.lcd_3_15.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_15.setObjectName(_fromUtf8("lcd_3_15"))
        self.lcd_3_16 = QtGui.QLabel(self.group_line3)
        self.lcd_3_16.setGeometry(QtCore.QRect(288, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_16.setFont(font)
        self.lcd_3_16.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_16.setLineWidth(0)
        self.lcd_3_16.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_16.setObjectName(_fromUtf8("lcd_3_16"))
        self.lcd_3_17 = QtGui.QLabel(self.group_line3)
        self.lcd_3_17.setGeometry(QtCore.QRect(306, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_17.setFont(font)
        self.lcd_3_17.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_17.setLineWidth(0)
        self.lcd_3_17.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_17.setObjectName(_fromUtf8("lcd_3_17"))
        self.lcd_3_18 = QtGui.QLabel(self.group_line3)
        self.lcd_3_18.setGeometry(QtCore.QRect(324, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_18.setFont(font)
        self.lcd_3_18.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_18.setLineWidth(0)
        self.lcd_3_18.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_18.setObjectName(_fromUtf8("lcd_3_18"))
        self.lcd_3_19 = QtGui.QLabel(self.group_line3)
        self.lcd_3_19.setGeometry(QtCore.QRect(342, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_19.setFont(font)
        self.lcd_3_19.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_19.setLineWidth(0)
        self.lcd_3_19.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_19.setObjectName(_fromUtf8("lcd_3_19"))
        self.lcd_3_0 = QtGui.QLabel(self.group_line3)
        self.lcd_3_0.setGeometry(QtCore.QRect(0, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_3_0.setFont(font)
        self.lcd_3_0.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_3_0.setLineWidth(0)
        self.lcd_3_0.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_3_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_3_0.setObjectName(_fromUtf8("lcd_3_0"))
        self.group_line0 = QtGui.QGroupBox(self.centralwidget)
        self.group_line0.setGeometry(QtCore.QRect(370, 122, 360, 32))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.group_line0.setFont(font)
        self.group_line0.setStyleSheet(_fromUtf8("border: 0px"))
        self.group_line0.setTitle(_fromUtf8(""))
        self.group_line0.setFlat(False)
        self.group_line0.setObjectName(_fromUtf8("group_line0"))
        self.lcd_0_1 = QtGui.QLabel(self.group_line0)
        self.lcd_0_1.setGeometry(QtCore.QRect(18, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_1.setFont(font)
        self.lcd_0_1.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_1.setLineWidth(0)
        self.lcd_0_1.setTextFormat(QtCore.Qt.RichText)
        self.lcd_0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_1.setObjectName(_fromUtf8("lcd_0_1"))
        self.lcd_0_2 = QtGui.QLabel(self.group_line0)
        self.lcd_0_2.setGeometry(QtCore.QRect(36, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_2.setFont(font)
        self.lcd_0_2.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_2.setLineWidth(0)
        self.lcd_0_2.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_2.setObjectName(_fromUtf8("lcd_0_2"))
        self.lcd_0_4 = QtGui.QLabel(self.group_line0)
        self.lcd_0_4.setGeometry(QtCore.QRect(72, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_4.setFont(font)
        self.lcd_0_4.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_4.setLineWidth(0)
        self.lcd_0_4.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_4.setObjectName(_fromUtf8("lcd_0_4"))
        self.lcd_0_5 = QtGui.QLabel(self.group_line0)
        self.lcd_0_5.setGeometry(QtCore.QRect(90, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_5.setFont(font)
        self.lcd_0_5.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_5.setLineWidth(0)
        self.lcd_0_5.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_5.setObjectName(_fromUtf8("lcd_0_5"))
        self.lcd_0_6 = QtGui.QLabel(self.group_line0)
        self.lcd_0_6.setGeometry(QtCore.QRect(108, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_6.setFont(font)
        self.lcd_0_6.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_6.setLineWidth(0)
        self.lcd_0_6.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_6.setObjectName(_fromUtf8("lcd_0_6"))
        self.lcd_0_7 = QtGui.QLabel(self.group_line0)
        self.lcd_0_7.setGeometry(QtCore.QRect(126, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_7.setFont(font)
        self.lcd_0_7.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_7.setLineWidth(0)
        self.lcd_0_7.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_7.setObjectName(_fromUtf8("lcd_0_7"))
        self.lcd_0_8 = QtGui.QLabel(self.group_line0)
        self.lcd_0_8.setGeometry(QtCore.QRect(144, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_8.setFont(font)
        self.lcd_0_8.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_8.setLineWidth(0)
        self.lcd_0_8.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_8.setObjectName(_fromUtf8("lcd_0_8"))
        self.lcd_0_9 = QtGui.QLabel(self.group_line0)
        self.lcd_0_9.setGeometry(QtCore.QRect(162, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_9.setFont(font)
        self.lcd_0_9.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_9.setLineWidth(0)
        self.lcd_0_9.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_9.setObjectName(_fromUtf8("lcd_0_9"))
        self.lcd_0_10 = QtGui.QLabel(self.group_line0)
        self.lcd_0_10.setGeometry(QtCore.QRect(180, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_10.setFont(font)
        self.lcd_0_10.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_10.setLineWidth(0)
        self.lcd_0_10.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_10.setObjectName(_fromUtf8("lcd_0_10"))
        self.lcd_0_11 = QtGui.QLabel(self.group_line0)
        self.lcd_0_11.setGeometry(QtCore.QRect(198, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_11.setFont(font)
        self.lcd_0_11.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_11.setLineWidth(0)
        self.lcd_0_11.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_11.setObjectName(_fromUtf8("lcd_0_11"))
        self.lcd_0_12 = QtGui.QLabel(self.group_line0)
        self.lcd_0_12.setGeometry(QtCore.QRect(216, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_12.setFont(font)
        self.lcd_0_12.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_12.setLineWidth(0)
        self.lcd_0_12.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_12.setObjectName(_fromUtf8("lcd_0_12"))
        self.lcd_0_13 = QtGui.QLabel(self.group_line0)
        self.lcd_0_13.setGeometry(QtCore.QRect(234, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_13.setFont(font)
        self.lcd_0_13.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_13.setLineWidth(0)
        self.lcd_0_13.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_13.setObjectName(_fromUtf8("lcd_0_13"))
        self.lcd_0_14 = QtGui.QLabel(self.group_line0)
        self.lcd_0_14.setGeometry(QtCore.QRect(252, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_14.setFont(font)
        self.lcd_0_14.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_14.setLineWidth(0)
        self.lcd_0_14.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_14.setObjectName(_fromUtf8("lcd_0_14"))
        self.lcd_0_15 = QtGui.QLabel(self.group_line0)
        self.lcd_0_15.setGeometry(QtCore.QRect(270, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_15.setFont(font)
        self.lcd_0_15.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_15.setLineWidth(0)
        self.lcd_0_15.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_15.setObjectName(_fromUtf8("lcd_0_15"))
        self.lcd_0_16 = QtGui.QLabel(self.group_line0)
        self.lcd_0_16.setGeometry(QtCore.QRect(288, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_16.setFont(font)
        self.lcd_0_16.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_16.setLineWidth(0)
        self.lcd_0_16.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_16.setObjectName(_fromUtf8("lcd_0_16"))
        self.lcd_0_17 = QtGui.QLabel(self.group_line0)
        self.lcd_0_17.setGeometry(QtCore.QRect(306, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_17.setFont(font)
        self.lcd_0_17.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_17.setLineWidth(0)
        self.lcd_0_17.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_17.setObjectName(_fromUtf8("lcd_0_17"))
        self.lcd_0_18 = QtGui.QLabel(self.group_line0)
        self.lcd_0_18.setGeometry(QtCore.QRect(324, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_18.setFont(font)
        self.lcd_0_18.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_18.setLineWidth(0)
        self.lcd_0_18.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_18.setObjectName(_fromUtf8("lcd_0_18"))
        self.lcd_0_19 = QtGui.QLabel(self.group_line0)
        self.lcd_0_19.setGeometry(QtCore.QRect(342, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_19.setFont(font)
        self.lcd_0_19.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_19.setLineWidth(0)
        self.lcd_0_19.setTextFormat(QtCore.Qt.PlainText)
        self.lcd_0_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_19.setObjectName(_fromUtf8("lcd_0_19"))
        self.lcd_0_3 = QtGui.QLabel(self.group_line0)
        self.lcd_0_3.setGeometry(QtCore.QRect(54, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_3.setFont(font)
        self.lcd_0_3.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_3.setLineWidth(0)
        self.lcd_0_3.setText(_fromUtf8(""))
        self.lcd_0_3.setTextFormat(QtCore.Qt.RichText)
        self.lcd_0_3.setScaledContents(True)
        self.lcd_0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_3.setIndent(0)
        self.lcd_0_3.setObjectName(_fromUtf8("lcd_0_3"))
        self.lcd_0_0 = QtGui.QLabel(self.group_line0)
        self.lcd_0_0.setGeometry(QtCore.QRect(0, 0, 17, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_0_0.setFont(font)
        self.lcd_0_0.setStyleSheet(_fromUtf8("color: rgb(0, 255, 255)"))
        self.lcd_0_0.setLineWidth(0)
        self.lcd_0_0.setTextFormat(QtCore.Qt.RichText)
        self.lcd_0_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lcd_0_0.setObjectName(_fromUtf8("lcd_0_0"))
        self.background.raise_()
        self.groupBox.raise_()
        self.dial.raise_()
        self.power_button.raise_()
        self.QC_up.raise_()
        self.QC_right.raise_()
        self.QC_left.raise_()
        self.QC_down.raise_()
        self.QC_next.raise_()
        self.groupNumbers.raise_()
        self.group_line1.raise_()
        self.lcd_1_1.raise_()
        self.group_line2.raise_()
        self.group_line3.raise_()
        self.group_line0.raise_()
        self.lcd_0_2.raise_()
        self.lcd_0_0.raise_()
        QC9520.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(QC9520)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        QC9520.setStatusBar(self.statusbar)

        self.retranslateUi(QC9520)
        QtCore.QMetaObject.connectSlotsByName(QC9520)

    def retranslateUi(self, QC9520):
        QC9520.setWindowTitle(_translate("QC9520", "QC9520", None))
        self.lcd_1_1.setText(_translate("QC9520", "y", None))
        self.lcd_1_2.setText(_translate("QC9520", "n", None))
        self.lcd_1_3.setText(_translate("QC9520", "c", None))
        self.lcd_1_4.setText(_translate("QC9520", " ", None))
        self.lcd_1_5.setText(_translate("QC9520", "S", None))
        self.lcd_1_6.setText(_translate("QC9520", "o", None))
        self.lcd_1_7.setText(_translate("QC9520", "u", None))
        self.lcd_1_8.setText(_translate("QC9520", "r", None))
        self.lcd_1_9.setText(_translate("QC9520", "c", None))
        self.lcd_1_10.setText(_translate("QC9520", "e", None))
        self.lcd_1_11.setText(_translate("QC9520", ":", None))
        self.lcd_1_12.setText(_translate("QC9520", " ", None))
        self.lcd_1_13.setText(_translate("QC9520", "T", None))
        self.lcd_1_14.setText(_translate("QC9520", "o", None))
        self.lcd_1_15.setText(_translate("QC9520", " ", None))
        self.lcd_1_16.setText(_translate("QC9520", " ", None))
        self.lcd_1_17.setText(_translate("QC9520", " ", None))
        self.lcd_1_18.setText(_translate("QC9520", " ", None))
        self.lcd_1_19.setText(_translate("QC9520", " ", None))
        self.lcd_1_0.setText(_translate("QC9520", "S", None))
        self.lcd_2_1.setText(_translate("QC9520", "i", None))
        self.lcd_2_2.setText(_translate("QC9520", "d", None))
        self.lcd_2_3.setText(_translate("QC9520", ":", None))
        self.lcd_2_4.setText(_translate("QC9520", " ", None))
        self.lcd_2_5.setText(_translate("QC9520", " ", None))
        self.lcd_2_6.setText(_translate("QC9520", " ", None))
        self.lcd_2_7.setText(_translate("QC9520", "0", None))
        self.lcd_2_8.setText(_translate("QC9520", ".", None))
        self.lcd_2_9.setText(_translate("QC9520", "0", None))
        self.lcd_2_10.setText(_translate("QC9520", "0", None))
        self.lcd_2_11.setText(_translate("QC9520", "0", None))
        self.lcd_2_12.setText(_translate("QC9520", "0", None))
        self.lcd_2_13.setText(_translate("QC9520", "0", None))
        self.lcd_2_14.setText(_translate("QC9520", "1", None))
        self.lcd_2_15.setText(_translate("QC9520", "0", None))
        self.lcd_2_16.setText(_translate("QC9520", "0", None))
        self.lcd_2_17.setText(_translate("QC9520", "0", None))
        self.lcd_2_18.setText(_translate("QC9520", "0", None))
        self.lcd_2_19.setText(_translate("QC9520", "0", None))
        self.lcd_2_0.setText(_translate("QC9520", "W", None))
        self.lcd_3_1.setText(_translate("QC9520", "l", None))
        self.lcd_3_2.setText(_translate("QC9520", "y", None))
        self.lcd_3_3.setText(_translate("QC9520", ":", None))
        self.lcd_3_4.setText(_translate("QC9520", " ", None))
        self.lcd_3_5.setText(_translate("QC9520", " ", None))
        self.lcd_3_6.setText(_translate("QC9520", " ", None))
        self.lcd_3_7.setText(_translate("QC9520", "0", None))
        self.lcd_3_8.setText(_translate("QC9520", ".", None))
        self.lcd_3_9.setText(_translate("QC9520", "0", None))
        self.lcd_3_10.setText(_translate("QC9520", "0", None))
        self.lcd_3_11.setText(_translate("QC9520", "0", None))
        self.lcd_3_12.setText(_translate("QC9520", "0", None))
        self.lcd_3_13.setText(_translate("QC9520", "0", None))
        self.lcd_3_14.setText(_translate("QC9520", "0", None))
        self.lcd_3_15.setText(_translate("QC9520", "0", None))
        self.lcd_3_16.setText(_translate("QC9520", "0", None))
        self.lcd_3_17.setText(_translate("QC9520", "0", None))
        self.lcd_3_18.setText(_translate("QC9520", "0", None))
        self.lcd_3_19.setText(_translate("QC9520", "0", None))
        self.lcd_3_0.setText(_translate("QC9520", "D", None))
        self.lcd_0_1.setText(_translate("QC9520", "|", None))
        self.lcd_0_2.setText(_translate("QC9520", "*", None))
        self.lcd_0_4.setText(_translate("QC9520", "]", None))
        self.lcd_0_5.setText(_translate("QC9520", " ", None))
        self.lcd_0_6.setText(_translate("QC9520", "E", None))
        self.lcd_0_7.setText(_translate("QC9520", "n", None))
        self.lcd_0_8.setText(_translate("QC9520", "a", None))
        self.lcd_0_9.setText(_translate("QC9520", "b", None))
        self.lcd_0_10.setText(_translate("QC9520", "l", None))
        self.lcd_0_11.setText(_translate("QC9520", "e", None))
        self.lcd_0_12.setText(_translate("QC9520", "d", None))
        self.lcd_0_13.setText(_translate("QC9520", " ", None))
        self.lcd_0_14.setText(_translate("QC9520", " ", None))
        self.lcd_0_15.setText(_translate("QC9520", " ", None))
        self.lcd_0_16.setText(_translate("QC9520", " ", None))
        self.lcd_0_17.setText(_translate("QC9520", "C", None))
        self.lcd_0_18.setText(_translate("QC9520", "h", None))
        self.lcd_0_19.setText(_translate("QC9520", "A", None))
        self.lcd_0_0.setText(_translate("QC9520", "[", None))

import QC9520_rc
